### ISSUE TITLE
error: Can't find meta/_journal.json file

### ISSUE THREAD

**Issue by FDiskas** [thecodebrew/bun-elysia-drizzle-base#1]
Tried on https://railway.app - it crashes
```
error: Can't find meta/_journal.json file

at readMigrationFiles (/app/node_modules/drizzle-orm/migrator.js:19:11)

at /app/node_modules/drizzle-orm/node-postgres/migrator.js:3:22

at migrate (/app/node_modules/drizzle-orm/node-postgres/migrator.js:2:24)

at /app/src/db/migrate.ts:11:9

at main (/app/src/db/migrate.ts:5:20)

at /app/src/db/migrate.ts:18:1

$ bun run src/db/migrate.ts

[migrate] Running migrations ...

14 |     throw new Error("no migration folder defined");

15 |   }

16 |   const migrationQueries = [];

17 |   const journalPath = `${migrationFolderTo}/meta/_journal.json`;

18 |   if (!fs.existsSync(journalPath)) {

19 |     throw new Error(`Can't find meta/_journal.json file`);

^

error: Can't find meta/_journal.json file

at readMigrationFiles (/app/node_modules/drizzle-orm/migrator.js:19:11)

at /app/node_modules/drizzle-orm/node-postgres/migrator.js:3:22

at migrate (/app/node_modules/drizzle-orm/node-postgres/migrator.js:2:24)

at /app/src/db/migrate.ts:11:9

at main (/app/src/db/migrate.ts:5:20)

at /app/src/db/migrate.ts:18:1

$ bun run src/db/migrate.ts

[migrate] Running migrations ...

14 |     throw new Error("no migration folder defined");

15 |   }

16 |   const migrationQueries = [];

17 |   const journalPath = `${migrationFolderTo}/meta/_journal.json`;

18 |   if (!fs.existsSync(journalPath)) {

19 |     throw new Error(`Can't find meta/_journal.json file`);

^

error: Can't find meta/_journal.json file

at readMigrationFiles (/app/node_modules/drizzle-orm/migrator.js:19:11)

at /app/node_modules/drizzle-orm/node-postgres/migrator.js:3:22

at migrate (/app/node_modules/drizzle-orm/node-postgres/migrator.js:2:24)

at /app/src/db/migrate.ts:11:9

at main (/app/src/db/migrate.ts:5:20)

at /app/src/db/migrate.ts:18:1

$ bun run src/db/migrate.ts

[migrate] Running migrations ...

14 |     throw new Error("no migration folder defined");

15 |   }

16 |   const migrationQueries = [];

17 |   const journalPath = `${migrationFolderTo}/meta/_journal.json`;

18 |   if (!fs.existsSync(journalPath)) {

19 |     throw new Error(`Can't find meta/_journal.json file`);

^

error: Can't find meta/_journal.json file

at readMigrationFiles (/app/node_modules/drizzle-orm/migrator.js:19:11)

at /app/node_modules/drizzle-orm/node-postgres/migrator.js:3:22

at migrate (/app/node_modules/drizzle-orm/node-postgres/migrator.js:2:24)

at /app/src/db/migrate.ts:11:9

at main (/app/src/db/migrate.ts:5:20)

at /app/src/db/migrate.ts:18:1

$ bun run src/db/migrate.ts

[migrate] Running migrations ...

14 |     throw new Error("no migration folder defined");

15 |   }

16 |   const migrationQueries = [];

17 |   const journalPath = `${migrationFolderTo}/meta/_journal.json`;

18 |   if (!fs.existsSync(journalPath)) {

19 |     throw new Error(`Can't find meta/_journal.json file`);

^

error: Can't find meta/_journal.json file

at readMigrationFiles (/app/node_modules/drizzle-orm/migrator.js:19:11)
```

**Comment by cdbrw** [comment]
Hey, you need to follow the setup guide in order to get the template started. The goal here is to have a base for your code to build off of easily while also not adding unnecessary tables to your database. You can easily be up and running with the following steps:

1. Clone the repository that was created by Railway 
2. In `/src/db/schema/index.ts` follow the instructions there. Add the tables you want for your database.
3. Run `bun run generate` to generate your migrations folder. This is the error you are encountering. Since you don't have any migrations and a migrations folder, the deploy is erroring out.
4. Push the changes to your repo to trigger another deploy.

That's all! If you're having difficulties with the setup, check out the instruction video I made for this [here](https://youtu.be/fZyAx97hzfw). Feel free to skip to the Railway section.
